apiVersion: v2
name: gloo
description: Feature-filled edge proxy to handle disparate services in the cluster.
version: 1.20.3-rev0
dependencies:
    - name: gloo
      version: 1.20.3
      repository: https://storage.googleapis.com/solo-public-helm
